=== Trampoline-CX/Cubes/src/theme/__GENERATED__/theme-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "definitions": {
    "ComplexColor": {
      "additionalProperties": false,
      "description": "Represents a complex color that has a base, light and dark value.",
      "properties": {
        "darker": {
          "description": "Type for a color. Used for readability purpose.",
          "pattern": "^(#[A-Fa-f0-9]{6}|transparent|rgba\\((\\d+(\\.\\d+)?,){3}(\\d+(\\.\\d+)?)\\))$",
          "type": "string"
        },
        "default": {
          "description": "Type for a color. Used for readability purpose.",
          "pattern": "^(#[A-Fa-f0-9]{6}|transparent|rgba\\((\\d+(\\.\\d+)?,){3}(\\d+(\\.\\d+)?)\\))$",
          "type": "string"
        },
        "lighter": {
          "description": "Type for a color. Used for readability purpose.",
          "pattern": "^(#[A-Fa-f0-9]{6}|transparent|rgba\\((\\d+(\\.\\d+)?,){3}(\\d+(\\.\\d+)?)\\))$",
          "type": "string"
        }
      },
      "required": ["darker", "default", "lighter"],
      "type": "object"
    },
    "Easing": {
      "enum": ["ease-in", "ease-in-out", "ease-out"],
      "type": "string"
    },
    "FontSize": {
      "additionalProperties": false,
      "properties": {
        "height": {
          "type": "number"
        },
        "size": {
          "type": "number"
        }
      },
      "required": ["height", "size"],
      "type": "object"
    },
    "FontWeight": {
      "description": "Type for a font-weight.",
      "enum": ["100", "200", "300", "400", "500", "600", "700", "800", "900", "bold", "normal"],
      "type": "string"
    }
  },
  "description": "Structure of a Theme.",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "animation": {
      "additionalProperties": false,
      "properties": {
        "duration": {
          "additionalProperties": false,
          "properties": {
            "default": {
              "type": "number"
            },
            "longer": {
              "type": "number"
            },
            "shorter": {
              "type": "number"
            }
          },
          "required": ["default", "longer", "shorter"],
          "type": "object"
        },
        "easing": {
          "additionalProperties": false,
          "properties": {
            "enter": {
              "$ref": "#/definitions/Easing"
            },
            "exit": {
              "$ref": "#/definitions/Easing"
            },
            "move": {
              "$ref": "#/definitions/Easing"
            }
          },
          "required": ["enter", "exit", "move"],
          "type": "object"
        }
      },
      "required": ["duration", "easing"],
      "type": "object"
    },
    "border": {
      "additionalProperties": false,
      "properties": {
        "none": {
          "type": "number"
        },
        "small": {
          "type": "number"
        },
        "thinner": {
          "type": "number"
        }
      },
      "required": ["none", "small", "thinner"],
      "type": "object"
    },
    "colors": {
      "additionalProperties": false,
      "properties": {
        "destructive": {
          "description": "Type for a color. Used for readability purpose.",
          "pattern": "^(#[A-Fa-f0-9]{6}|transparent|rgba\\((\\d+(\\.\\d+)?,){3}(\\d+(\\.\\d+)?)\\))$",
          "type": "string"
        },
        "fill": {
          "additionalProperties": false,
          "properties": {
            "accent": {
              "$ref": "#/definitions/ComplexColor"
            },
            "accentSecondary": {
              "$ref": "#/definitions/ComplexColor"
            },
            "background": {
              "additionalProperties": false,
              "properties": {
                "darker": {
                  "description": "Type for a color. Used for readability purpose.",
                  "pattern": "^(#[A-Fa-f0-9]{6}|transparent|rgba\\((\\d+(\\.\\d+)?,){3}(\\d+(\\.\\d+)?)\\))$",
                  "type": "string"
                },
                "default": {
                  "description": "Type for a color. Used for readability purpose.",
                  "pattern": "^(#[A-Fa-f0-9]{6}|transparent|rgba\\((\\d+(\\.\\d+)?,){3}(\\d+(\\.\\d+)?)\\))$",
                  "type": "string"
                },
                "inverse": {
                  "description": "Type for a color. Used for readability purpose.",
                  "pattern": "^(#[A-Fa-f0-9]{6}|transparent|rgba\\((\\d+(\\.\\d+)?,){3}(\\d+(\\.\\d+)?)\\))$",
                  "type": "string"
                },
                "lighter": {
                  "description": "Type for a color. Used for readability purpose.",
                  "pattern": "^(#[A-Fa-f0-9]{6}|transparent|rgba\\((\\d+(\\.\\d+)?,){3}(\\d+(\\.\\d+)?)\\))$",
                  "type": "string"
                }
              },
              "required": ["darker", "default", "inverse", "lighter"],
              "type": "object"
            },
            "divider": {
              "$ref": "#/definitions/ComplexColor"
            },
            "primary": {
              "$ref": "#/definitions/ComplexColor"
            }
          },
          "required": ["accent", "accentSecondary", "background", "divider", "primary"],
          "type": "object"
        },
        "negative": {
          "description": "Type for a color. Used for readability purpose.",
          "pattern": "^(#[A-Fa-f0-9]{6}|transparent|rgba\\((\\d+(\\.\\d+)?,){3}(\\d+(\\.\\d+)?)\\))$",
          "type": "string"
        },
        "positive": {
          "description": "Type for a color. Used for readability purpose.",
          "pattern": "^(#[A-Fa-f0-9]{6}|transparent|rgba\\((\\d+(\\.\\d+)?,){3}(\\d+(\\.\\d+)?)\\))$",
          "type": "string"
        },
        "status": {
          "additionalProperties": false,
          "properties": {
            "error": {
              "description": "Type for a color. Used for readability purpose.",
              "pattern": "^(#[A-Fa-f0-9]{6}|transparent|rgba\\((\\d+(\\.\\d+)?,){3}(\\d+(\\.\\d+)?)\\))$",
              "type": "string"
            },
            "success": {
              "$ref": "#/definitions/ComplexColor"
            },
            "warning": {
              "description": "Type for a color. Used for readability purpose.",
              "pattern": "^(#[A-Fa-f0-9]{6}|transparent|rgba\\((\\d+(\\.\\d+)?,){3}(\\d+(\\.\\d+)?)\\))$",
              "type": "string"
            }
          },
          "required": ["error", "success", "warning"],
          "type": "object"
        },
        "text": {
          "additionalProperties": false,
          "properties": {
            "accent": {
              "description": "Type for a color. Used for readability purpose.",
              "pattern": "^(#[A-Fa-f0-9]{6}|transparent|rgba\\((\\d+(\\.\\d+)?,){3}(\\d+(\\.\\d+)?)\\))$",
              "type": "string"
            },
            "inverse": {
              "description": "Type for a color. Used for readability purpose.",
              "pattern": "^(#[A-Fa-f0-9]{6}|transparent|rgba\\((\\d+(\\.\\d+)?,){3}(\\d+(\\.\\d+)?)\\))$",
              "type": "string"
            },
            "primary": {
              "description": "Type for a color. Used for readability purpose.",
              "pattern": "^(#[A-Fa-f0-9]{6}|transparent|rgba\\((\\d+(\\.\\d+)?,){3}(\\d+(\\.\\d+)?)\\))$",
              "type": "string"
            },
            "subdued": {
              "description": "Type for a color. Used for readability purpose.",
              "pattern": "^(#[A-Fa-f0-9]{6}|transparent|rgba\\((\\d+(\\.\\d+)?,){3}(\\d+(\\.\\d+)?)\\))$",
              "type": "string"
            }
          },
          "required": ["accent", "inverse", "primary", "subdued"],
          "type": "object"
        },
        "transparent": {
          "description": "Type for a color. Used for readability purpose.",
          "pattern": "^(#[A-Fa-f0-9]{6}|transparent|rgba\\((\\d+(\\.\\d+)?,){3}(\\d+(\\.\\d+)?)\\))$",
          "type": "string"
        }
      },
      "required": ["destructive", "fill", "negative", "positive", "status", "text", "transparent"],
      "type": "object"
    },
    "elevation": {
      "additionalProperties": false,
      "properties": {
        "z0": {
          "additionalProperties": false,
          "description": "Type representing an Elevation.",
          "properties": {
            "elevation": {
              "description": "Sets the elevation of a view, using Android's underlying\n[elevation API](https://developer.android.com/training/material/shadows-clipping.html#Elevation).\nThis adds a drop shadow to the item and affects z-order for overlapping views.\nOnly supported on Android 5.0+, has no effect on earlier versions.",
              "type": "number"
            },
            "shadowColor": {
              "type": "string"
            },
            "shadowOffset": {
              "additionalProperties": false,
              "properties": {
                "height": {
                  "type": "number"
                },
                "width": {
                  "type": "number"
                }
              },
              "required": ["height", "width"],
              "type": "object"
            },
            "shadowOpacity": {
              "type": "number"
            },
            "shadowRadius": {
              "type": "number"
            }
          },
          "required": ["elevation"],
          "type": "object"
        },
        "z2": {
          "additionalProperties": false,
          "description": "Type representing an Elevation.",
          "properties": {
            "elevation": {
              "description": "Sets the elevation of a view, using Android's underlying\n[elevation API](https://developer.android.com/training/material/shadows-clipping.html#Elevation).\nThis adds a drop shadow to the item and affects z-order for overlapping views.\nOnly supported on Android 5.0+, has no effect on earlier versions.",
              "type": "number"
            },
            "shadowColor": {
              "type": "string"
            },
            "shadowOffset": {
              "additionalProperties": false,
              "properties": {
                "height": {
                  "type": "number"
                },
                "width": {
                  "type": "number"
                }
              },
              "required": ["height", "width"],
              "type": "object"
            },
            "shadowOpacity": {
              "type": "number"
            },
            "shadowRadius": {
              "type": "number"
            }
          },
          "required": ["elevation"],
          "type": "object"
        },
        "z4": {
          "additionalProperties": false,
          "description": "Type representing an Elevation.",
          "properties": {
            "elevation": {
              "description": "Sets the elevation of a view, using Android's underlying\n[elevation API](https://developer.android.com/training/material/shadows-clipping.html#Elevation).\nThis adds a drop shadow to the item and affects z-order for overlapping views.\nOnly supported on Android 5.0+, has no effect on earlier versions.",
              "type": "number"
            },
            "shadowColor": {
              "type": "string"
            },
            "shadowOffset": {
              "additionalProperties": false,
              "properties": {
                "height": {
                  "type": "number"
                },
                "width": {
                  "type": "number"
                }
              },
              "required": ["height", "width"],
              "type": "object"
            },
            "shadowOpacity": {
              "type": "number"
            },
            "shadowRadius": {
              "type": "number"
            }
          },
          "required": ["elevation"],
          "type": "object"
        },
        "z8": {
          "additionalProperties": false,
          "description": "Type representing an Elevation.",
          "properties": {
            "elevation": {
              "description": "Sets the elevation of a view, using Android's underlying\n[elevation API](https://developer.android.com/training/material/shadows-clipping.html#Elevation).\nThis adds a drop shadow to the item and affects z-order for overlapping views.\nOnly supported on Android 5.0+, has no effect on earlier versions.",
              "type": "number"
            },
            "shadowColor": {
              "type": "string"
            },
            "shadowOffset": {
              "additionalProperties": false,
              "properties": {
                "height": {
                  "type": "number"
                },
                "width": {
                  "type": "number"
                }
              },
              "required": ["height", "width"],
              "type": "object"
            },
            "shadowOpacity": {
              "type": "number"
            },
            "shadowRadius": {
              "type": "number"
            }
          },
          "required": ["elevation"],
          "type": "object"
        }
      },
      "required": ["z0", "z2", "z4", "z8"],
      "type": "object"
    },
    "font": {
      "additionalProperties": false,
      "properties": {
        "family": {
          "description": "Type for a font-family. Used for readability purpose.",
          "type": "string"
        },
        "size": {
          "additionalProperties": false,
          "properties": {
            "large": {
              "$ref": "#/definitions/FontSize"
            },
            "regular": {
              "$ref": "#/definitions/FontSize"
            },
            "small": {
              "$ref": "#/definitions/FontSize"
            }
          },
          "required": ["large", "regular", "small"],
          "type": "object"
        },
        "weights": {
          "additionalProperties": false,
          "properties": {
            "regular": {
              "$ref": "#/definitions/FontWeight"
            },
            "strong": {
              "$ref": "#/definitions/FontWeight"
            }
          },
          "required": ["regular", "strong"],
          "type": "object"
        }
      },
      "required": ["family", "size", "weights"],
      "type": "object"
    },
    "opacity": {
      "additionalProperties": false,
      "properties": {
        "disabled": {
          "type": "number"
        }
      },
      "required": ["disabled"],
      "type": "object"
    },
    "radius": {
      "additionalProperties": false,
      "properties": {
        "circle": {
          "type": "number"
        },
        "large": {
          "type": "number"
        },
        "medium": {
          "type": "number"
        },
        "none": {
          "type": "number"
        },
        "small": {
          "type": "number"
        }
      },
      "required": ["circle", "large", "medium", "none", "small"],
      "type": "object"
    },
    "size": {
      "additionalProperties": false,
      "properties": {
        "avatar": {
          "additionalProperties": false,
          "properties": {
            "default": {
              "type": "number"
            },
            "small": {
              "type": "number"
            }
          },
          "required": ["default", "small"],
          "type": "object"
        },
        "bullet": {
          "type": "number"
        },
        "divider": {
          "type": "number"
        },
        "icon": {
          "additionalProperties": false,
          "properties": {
            "default": {
              "type": "number"
            },
            "large": {
              "type": "number"
            },
            "small": {
              "type": "number"
            },
            "xLarge": {
              "type": "number"
            }
          },
          "required": ["default", "large", "small", "xLarge"],
          "type": "object"
        },
        "minTouchArea": {
          "type": "number"
        }
      },
      "required": ["avatar", "bullet", "divider", "icon", "minTouchArea"],
      "type": "object"
    },
    "spacing": {
      "additionalProperties": false,
      "properties": {
        "large": {
          "type": "number"
        },
        "medium": {
          "type": "number"
        },
        "none": {
          "type": "number"
        },
        "small": {
          "type": "number"
        },
        "xLarge": {
          "type": "number"
        },
        "xSmall": {
          "type": "number"
        },
        "xxLarge": {
          "type": "number"
        }
      },
      "required": ["large", "medium", "none", "small", "xLarge", "xSmall", "xxLarge"],
      "type": "object"
    }
  },
  "required": [
    "$schema",
    "animation",
    "border",
    "colors",
    "elevation",
    "font",
    "opacity",
    "radius",
    "size",
    "spacing"
  ],
  "type": "object"
}

=== Trampoline-CX/Cubes/src/theme/light-theme.json
{
  "$schema": "./__GENERATED__/theme-schema.json",
  "colors": {
    "fill": {
      "primary": {
        "default": "#5B6275",
        "lighter": "#FFFFFF",
        "darker": "#FFFFFF"
      },
      "accent": {
        "default": "#EE5D71",
        "lighter": "#FFFFFF",
        "darker": "#FFFFFF"
      },
      "accentSecondary": {
        "default": "#F7B5A1",
        "lighter": "#FFE6DE",
        "darker": "#EA947A"
      },
      "background": {
        "default": "#FCF8F7",
        "lighter": "#FFFFFF",
        "darker": "#EDE9E4",
        "inverse": "#5B6275"
      },
      "divider": {
        "default": "rgba(0,0,0,0.10)",
        "lighter": "rgba(0,0,0,0.05)",
        "darker": "#303131"
      }
    },
    "text": {
      "primary": "#454B59",
      "accent": "#EE5D71",
      "subdued": "#888888",
      "inverse": "#FFFFFF"
    },
    "transparent": "transparent",
    "destructive": "#FF0000",
    "positive": "#63A84C",
    "negative": "#D32F2F",
    "status": {
      "success": {
        "default": "#A5DBCA",
        "lighter": "#D3E3DE",
        "darker": "#6BBFA5"
      },
      "warning": "#FAD1A2",
      "error": "#FF0000"
    }
  },

  "font": {
    "family": "System",
    "size": {
      "large": {
        "size": 24,
        "height": 32
      },
      "regular": {
        "size": 16,
        "height": 24
      },
      "small": {
        "size": 12,
        "height": 16
      }
    },
    "weights": {
      "regular": "400",
      "strong": "700"
    }
  },

  "opacity": {
    "disabled": 0.6
  },

  "border": {
    "thinner": 1,
    "small": 2,
    "none": 0
  },

  "elevation": {
    "z0": {
      "shadowOpacity": 0,
      "shadowRadius": 0,
      "shadowColor": "#000",
      "elevation": 0
    },
    "z2": {
      "shadowOffset": { "width": 0, "height": 1 },
      "shadowOpacity": 0.2,
      "shadowRadius": 1.5,
      "shadowColor": "#000",
      "elevation": 2
    },
    "z4": {
      "shadowOffset": { "width": 0, "height": 2 },
      "shadowOpacity": 0.22,
      "shadowRadius": 2.5,
      "shadowColor": "#000",
      "elevation": 4
    },
    "z8": {
      "shadowOffset": { "width": 0, "height": 3 },
      "shadowOpacity": 0.22,
      "shadowRadius": 4.5,
      "shadowColor": "#000",
      "elevation": 8
    }
  },

  "size": {
    "minTouchArea": 48,
    "icon": {
      "default": 24,
      "small": 16,
      "large": 48,
      "xLarge": 64
    },
    "avatar": {
      "default": 40,
      "small": 32
    },
    "divider": 1,
    "bullet": 8
  },

  "spacing": {
    "xxLarge": 40,
    "xLarge": 32,
    "large": 24,
    "medium": 16,
    "small": 8,
    "xSmall": 4,
    "none": 0
  },

  "radius": {
    "circle": 9999,
    "small": 2,
    "medium": 4,
    "large": 8,
    "none": 0
  },

  "animation": {
    "duration": {
      "default": 300,
      "shorter": 150,
      "longer": 400
    },
    "easing": {
      "enter": "ease-out",
      "exit": "ease-in",
      "move": "ease-in-out"
    }
  }
}
